services:
  - type: web
    name: budgetbuddy
    env: python
    buildCommand: cd budgetbuddy && pip install -r requirements.txt
    startCommand: gunicorn budgetbuddy.wsgi:application
    rootDir: .
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: budgetbuddy.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False